### PR TITLE
Mon 3630 service template macro

### LINKED ISSUE #7121: Custom check command, template and service
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
18.10.2

**Centreon Engine version**: 
centreon-engine-18.10.0

**Centreon Broker version**: 
centreon-broker-cbd-18.10.1

**OS**: 
CentOS7

**Steps to reproduce the issue:**
1. Create a check command with custom macros.
2. Create a template with the newly created check command.
3. Create a service with the newly created template.

**Describe the results you received:**
The macros are not appearing in the web interface for the new services when you select your template

**Describe the results you expected:**
Macros appears when you select your template

**Additional information you think important (e.g. issue happens only occasionally):**
If you add a centreon created template to the template you create, all the macros now appears in the interface when you select this template for your service (the macros from the centreon template and the macros from the custom one you created)

### PR DESCRIPTION
**Pull request by loiclau**
<h1> Pull Request Template </h1>

<h2> Description </h2>

get the origin service information, not only his children

Fixes #7121

<h2> Type of change </h2>

- [ ] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software
- [ ] Updating documentation (missing information, typo...)

<h2> Target serie </h2>

- [ ] 2.8.x
- [x] 18.10.x
- [x] 19.04.x (master)

<h2> How this pull request can be tested ? </h2>

Please describe the **procedure** to verify that the goal of the PR is matched. Provide clear instructions so that it can be **correctly tested**.

Any **relevant details** of the configuration to perform the test should be added.

<h2> Checklist </h2>

<h5> Community contributors & Centreon team </h5>

- [x] I followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [ ] I have made corresponding changes to the **documentation**.
- [ ] I have **rebased** my development branch on the base branch (master, maintenance).

<h5> Centreon team only </h5>

- [ ] I have made sure that the **unit tests** related to the story are successful.
- [ ] I have made sure that **unit tests covers 80%** of the code written for the story.
- [ ] I have made sure that **acceptance tests** related to the story are successful (**local and CI**)

### CODE REVIEW

File: www/include/common/common-Func.php [hunk 1]
```diff
@@ -2122,10 +2122,11 @@ function getListTemplates($pearDB, $svcId, $alreadyProcessed = array())
     } else {
         $alreadyProcessed[] = $svcId;
 
-        $query = "SELECT * FROM service WHERE service_id = " . intval($svcId);
+        $query = "SELECT * FROM service WHERE service_id = " . (int)$svcId;
         $stmt = $pearDB->query($query);
         if ($stmt->rowCount()) {
             $row = $stmt->fetchRow();
```
Comment (sc979) [inline www/include/common/common-Func.php]:
```suggestion
            $row = $stmt->fetch();
```
